var eventsDeck = {
'The loading of a resource has been aborted.':'abort',
'Progression has been terminated (not due to an error).':'abort',
'A transaction has been aborted.':'abort',
'The associated document has started printing or the print preview has been closed.':'afterprint',
'A CSS animation has completed.':'animationend',
'A CSS animation is repeated.':'animationiteration',
'A CSS animation has started.':'animationstart',
'The input buffer of a ScriptProcessorNode is ready to be processed.':'audioprocess',
'The user agent has finished capturing audio for speech recognition.':'audioend',
'The user agent has started to capture audio for speech recognition.':'audiostart',
'The associated document is about to be printed or previewed for printing.':'beforeprint ',
' ':'beforeunload',
'A SMIL animation element begins.':'beginEvent',
'An open connection to a database is blocking a versionchange transaction on the same database.':'blocked',
'An element has lost focus (does not bubble).':'blur',
'The spoken utterance reaches a word or sentence boundary':'boundary',
'The resources listed in the manifest have been downloaded, and the application is now cached.':'cached',
'The user agent can play the media, but estimates that not enough data has been loaded to play the media up to its end without having to stop for further buffering of content.':'canplay',
'The user agent can play the media, and estimates that enough data has been loaded to play the media up to its end without having to stop for further buffering of content.':'canplaythrough',
'The change event is fired for <input>, <select>, and <textarea> elements when a change to the element\'s value is committed by the user.':'change',
'The battery begins or stops charging.':'chargingchange',
'The chargingTime attribute has been updated.':'chargingtimechange',
'The user agent is checking for an update, or attempting to download the cache manifest for the first time.':'checking',
'A pointing device button has been pressed and released on an element.':'click',
'A WebSocket connection has been closed.':'close',
' ':'complete',
'The rendering of an OfflineAudioContext is terminated.':'complete',
'The composition of a passage of text has been completed or canceled.':'compositionend',
'The composition of a passage of text is prepared (similar to keydown for a keyboard input, but works with other inputs such as speech recognition).':'compositionstart',
'A character is added to a passage of text being composed.':'compositionupdate',
'The right button of the mouse is clicked (before the context menu is displayed).':'contextmenu',
'The text selection has been added to the clipboard.':'copy',
'The text selection has been removed from the document and added to the clipboard.':'cut',
'A pointing device button is clicked twice on an element.':'dblclick',
'Fresh data is available from a light sensor.':'devicelight',
'Fresh data is available from a motion sensor.':'devicemotion',
'Fresh data is available from an orientation sensor.':'deviceorientation',
'Fresh data is available from a proximity sensor (indicates an approximated distance between the device and a nearby object).':'deviceproximity',
'The dischargingTime attribute has been updated.':'dischargingtimechange',
'A button, link or state changing element is activated (use click instead).':'DOMActivate  ',
'The name of an attribute changed (use mutation observers instead).':'DOMAttributeNameChanged  ',
'The value of an attribute has been modified (use mutation observers instead).':'DOMAttrModified  ',
'A text or another CharacterData has changed (use mutation observers instead).':'DOMCharacterDataModified  ',
'The document has finished loading (but not its dependent resources).':'DOMContentLoaded',
'The name of an element changed (use mutation observers instead).':'DOMElementNameChanged  ',
'An element has received focus (use focus or focusin instead).':'DOMFocusIn   Unimplemented',
'An element has lost focus (use blur or focusout instead).':'DOMFocusOut   Unimplemented',
'A node has been added as a child of another node (use mutation observers instead).':'DOMNodeInserted  ',
'A node has been inserted into the document (use mutation observers instead).':'DOMNodeInsertedIntoDocument  ',
'A node has been removed from its parent node (use mutation observers instead).':'DOMNodeRemoved  ',
'A node has been removed from the document (use mutation observers instead).':'DOMNodeRemovedFromDocument  ',
'A change happened in the document (use mutation observers instead).':'DOMSubtreeModified  ',
'The user agent has found an update and is fetching it, or is downloading the resources listed by the cache manifest for the first time.':'downloading',
'An element or text selection is being dragged (every 350ms).':'drag',
'A drag operation is being ended (by releasing a mouse button or hitting the escape key).':'dragend',
'A dragged element or text selection enters a valid drop target.':'dragenter',
'A dragged element or text selection leaves a valid drop target.':'dragleave',
'An element or text selection is being dragged over a valid drop target (every 350ms).':'dragover',
'The user starts dragging an element or text selection.':'dragstart',
'An element is dropped on a valid drop target.':'drop',
'The duration attribute has been updated.':'durationchange',
'The media has become empty; for example, this event is sent if the media has already been loaded (or partially loaded), and the load() method is called to reload it.':'emptied',
'The speech recognition service has disconnected.':'end',
'The utterance has finished being spoken.':'end',
'Playback has stopped because the end of the media was reached.':'ended',
' ':'ended',
'A SMIL animation element ends.':'endEvent',
'A resource failed to load.':'error',
'Progression has failed.':'error',
'An error occurred while downloading the cache manifest or updating the content of the application.':'error',
'A WebSocket connection has been closed with prejudice (some data couldn\'t be sent for example).':'error',
'An event source connection has been failed.':'error',
'A request caused an error and failed.':'error',
'A speech recognition error occurs.':'error',
'An error occurs that prevents the utterance from being succesfully spoken.':'error',
'An element has received focus (does not bubble).':'focus',
'An element is about to receive focus (bubbles).':'focusinUnimplemented (see bug 687787)',
'An element is about to lose focus (bubbles).':'focusoutUnimplemented (see bug 687787)',
'An element was turned to fullscreen mode or back to normal mode.':'fullscreenchange',
'It was impossible to switch to fullscreen mode for technical reasons or because the permission was denied.':'fullscreenerror',
'A gamepad has been connected.':'gamepadconnected',
'A gamepad has been disconnected.':'gamepaddisconnected',
'Element receives pointer capture.':'gotpointercapture',
'The fragment identifier of the URL has changed (the part of the URL after the #).':'hashchange',
'Element lost pointer capture.':'lostpointercapture',
'The value of an element changes or the content of an element with the attribute contenteditable is modified.':'input',
'A submittable element has been checked and doesn\'t satisfy its constraints.':'invalid',
'A key is pressed down.':'keydown',
'A key is pressed down and that key normally produces a character value (use input instead).':'keypress',
'A key is released.':'keyup',
' ':'languagechange',
'The level attribute has been updated.':'levelchange',
'A resource and its dependent resources have finished loading.':'load',
'Progression has been successful.':'load',
'The first frame of the media has finished loading.':'loadeddata',
'The metadata has been loaded.':'loadedmetadata',
'Progress has stopped (after "error", "abort" or "load" have been dispatched).':'loadend',
'Progress has begun.':'loadstart',
'The spoken utterance reaches a named SSML "mark" tag.':'mark',
'A message is received through a WebSocket.':'message',
'A message is received from a Web Worker.':'message',
'A message is received from a child (i)frame or a parent window.':'message',
'A message is received through an event source.':'message',
'A message is received from a service worker, or a message is received in a service worker from another context.':'message',
'A pointing device button (usually a mouse) is pressed on an element.':'mousedown',
'A pointing device is moved onto the element that has the listener attached.':'mouseenter',
'A pointing device is moved off the element that has the listener attached.':'mouseleave',
'A pointing device is moved over an element.':'mousemove',
'A pointing device is moved off the element that has the listener attached or off one of its children.':'mouseout',
'A pointing device is moved onto the element that has the listener attached or onto one of its children.':'mouseover',
'A pointing device button is released over an element.':'mouseup',
'The speech recognition service returns a final result with no significant recognition.':'nomatch',
'A system notification spawned by ServiceWorkerRegistration.showNotification() has been clicked.':'notificationclick',
'The manifest hadn\'t changed.':'noupdate',
'The manifest was found to have become a 404 or 410 page, so the application cache is being deleted.':'obsolete',
'The browser has lost access to the network.':'offline',
'The browser has gained access to the network (but particular websites might be unreachable).':'online',
'A WebSocket connection has been established.':'open',
'An event source connection has been established.':'open',
'The orientation of the device (portrait/landscape) has changed':'orientationchange',
'A session history entry is being traversed from.':'pagehide',
'A session history entry is being traversed to.':'pageshow',
'Data has been transfered from the system clipboard to the document.':'paste',
'Playback has been paused.':'pause',
'The utterance is paused part way through.':'pause',
'The pointer is unlikely to produce any more events.':'pointercancel',
'The pointer enters the active buttons state.':'pointerdown',
'Pointing device is moved inside the hit-testing boundary.':'pointerenter',
'Pointing device is moved out of the hit-testing boundary.':'pointerleave',
'The pointer was locked or released.':'pointerlockchange',
'It was impossible to lock the pointer for technical reasons or because the permission was denied.':'pointerlockerror',
'The pointer changed coordinates.':'pointermove',
'The pointing device moved out of hit-testing boundary or leaves detectable hover range.':'pointerout',
'The pointing device is moved into the hit-testing boundary.':'pointerover',
'The pointer leaves the active buttons state.':'pointerup',
'Playback has begun.':'play',
'Playback is ready to start after having been paused or delayed due to lack of data.':'playing',
'A session history entry is being navigated to (in certain cases).':'popstate',
'In progress.':'progress',
'The user agent is downloading resources listed by the manifest.':'progress',
'A Service Worker has received a push message.':'push',
'A PushSubscription has expired.':'pushsubscriptionchange',
'The playback rate has changed.':'ratechange',
'The readyState attribute of a document has changed.':'readystatechange',
'A SMIL animation element is repeated.':'repeatEvent',
'A form is reset.':'reset',
'The document view has been resized.':'resize',
'The browser\'s resource timing buffer is full.':'resourcetimingbufferfull',
'The speech recognition service returns a result — a word or phrase has been positively recognized and this has been communicated back to the app.':'result',
'A paused utterance is resumed.':'resume',
'The document view or an element has been scrolled.':'scroll',
'A seek operation completed.':'seeked',
'A seek operation began.':'seeking',
'Some text is being selected.':'select',
'A selection just started.':'selectstart',
'The selection in the document has been changed.':'selectionchange',
'A contextmenu event was fired on/bubbled to an element that has a contextmenu attribute':'show',
'Any sound — recognisable speech or not — has stopped being detected.':'soundend',
'Any sound — recognisable speech or not — has been detected.':'soundstart',
'Speech recognised by the speech recognition service has stopped being detected.':'speechend',
'Sound that is recognised by the speech recognition service as speech has been detected.':'speechstart',
'The user agent is trying to fetch media data, but data is unexpectedly not forthcoming.':'stalled',
'The speech recognition service has begun listening to incoming audio with intent to recognize grammars associated with the current SpeechRecognition.':'start',
'The utterance has begun to be spoken.':'start',
'A storage area (localStorage or sessionStorage) has changed.':'storage',
'A form is submitted.':'submit',
'A request successfully completed.':'success',
'Media data loading has been suspended.':'suspend',
'Page loading has been stopped before the SVG was loaded.':'SVGAbort',
'An error has occurred before the SVG was loaded.':'SVGError',
'An SVG document has been loaded and parsed.':'SVGLoad',
'An SVG document is being resized.':'SVGResize',
'An SVG document is being scrolled.':'SVGScroll',
'An SVG document has been removed from a window or frame.':'SVGUnload',
'An SVG document is being zoomed.':'SVGZoom',
' ':'timeout',
'The time indicated by the currentTime attribute has been updated.':'timeupdate',
'A touch point has been disrupted in an implementation-specific manners (too many touch points for example).':'touchcancel',
'A touch point is removed from the touch surface.':'touchend',
'A touch point is moved onto the interactive area of an element.':'touchenter',
'A touch point is moved off the interactive area of an element.':'touchleave',
'A touch point is moved along the touch surface.':'touchmove',
'A touch point is placed on the touch surface.':'touchstart',
'A CSS transition has completed.':'transitionend',
'The document or a dependent resource is being unloaded.':'unload',
'The resources listed in the manifest have been newly redownloaded, and the script can use swapCache() to switch to the new cache.':'updateready',
'An attempt was made to open a database with a version number higher than its current version. A versionchange transaction has been created.':'upgradeneeded',
'Fresh data is available from a proximity sensor (indicates whether the nearby object is near the device or not).':'userproximity',
'The list of SpeechSynthesisVoice objects that would be returned by the SpeechSynthesis.getVoices() method has changed (when the voiceschanged event fires.)':'voiceschanged',
'A versionchange transaction completed.':'versionchange',
'The content of a tab has become visible or has been hidden.':'visibilitychange',
'The volume has changed.':'volumechange',
'Playback has stopped because of a temporary lack of data.':'waiting',
'A wheel button of a pointing device is rotated in any direction.':'wheel',
}